# Generated by Django 5.2.17 on 2026-08-04 18:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم العميل')),
                ('phone', models.CharField(max_length=30, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='accounts.workshop')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الخدمة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='السعر الأساسي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='accounts.workshop')),
            ],
            options={
                'verbose_name': 'خدمة',
                'verbose_name_plural': 'الخدمات',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=30, verbose_name='رقم اللوحة')),
                ('make', models.CharField(max_length=80, verbose_name='الشركة المصنعة')),
                ('model', models.CharField(max_length=80, verbose_name='الموديل')),
                ('model_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سنة الصنع')),
                ('vin', models.CharField(blank=True, max_length=50, verbose_name='رقم الهيكل')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='اللون')),
                ('mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='عداد الكيلومترات')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='workshop.customer')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='accounts.workshop')),
            ],
            options={
                'verbose_name': 'مركبة',
                'verbose_name_plural': 'المركبات',
                'ordering': ('license_plate',),
            },
        ),
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='رقم بطاقة العمل')),
                ('status', models.CharField(choices=[('pending', 'بانتظار الفحص'), ('in_progress', 'قيد الإصلاح'), ('ready', 'جاهزة للاستلام'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغاة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('complaint', models.TextField(verbose_name='وصف العطل')),
                ('diagnosis', models.TextField(blank=True, verbose_name='نتيجة الفحص')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='التكلفة التقديرية')),
                ('actual_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='التكلفة الفعلية')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاستلام')),
                ('promised_at', models.DateTimeField(blank=True, null=True, verbose_name='موعد الإنجاز المتوقع')),
                ('status_updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_technicians', models.ManyToManyField(blank=True, related_name='assigned_job_cards', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_job_cards', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_cards', to='workshop.customer')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='accounts.workshop')),
                ('services', models.ManyToManyField(blank=True, related_name='job_cards', to='workshop.service')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_cards', to='workshop.vehicle')),
            ],
            options={
                'verbose_name': 'بطاقة عمل',
                'verbose_name_plural': 'بطاقات العمل',
                'ordering': ('-received_at',),
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['workshop', 'name'], name='workshop_cu_worksho_370fee_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['workshop', 'phone'], name='workshop_cu_worksho_d56598_idx'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('workshop', 'name'), name='unique_service_per_workshop'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['workshop', 'vin'], name='workshop_ve_worksho_394ce1_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('workshop', 'license_plate'), name='unique_plate_per_workshop'),
        ),
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['workshop', 'status'], name='workshop_jo_worksho_658c98_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['workshop', 'received_at'], name='workshop_jo_worksho_d502bc_idx'),
        ),
    ]
