# Generated by Django 5.2.17 on 2026-08-04 19:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('workshop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم المورد')),
                ('contact_name', models.CharField(blank=True, max_length=150, verbose_name='جهة الاتصال')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='accounts.workshop')),
            ],
            options={
                'verbose_name': 'مورد',
                'verbose_name_plural': 'الموردون',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم القطعة')),
                ('sku', models.CharField(max_length=80, verbose_name='رمز القطعة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='الكمية المتاحة')),
                ('reorder_level', models.PositiveIntegerField(default=0, verbose_name='حد إعادة الطلب')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='سعر الشراء')),
                ('sale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='سعر البيع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='accounts.workshop')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='inventory.supplier')),
            ],
            options={
                'verbose_name': 'قطعة غيار',
                'verbose_name_plural': 'قطع الغيار',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='InventoryAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_at_alert', models.PositiveIntegerField()),
                ('reorder_level_at_alert', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='accounts.workshop')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.part')),
            ],
            options={
                'verbose_name': 'تنبيه مخزون',
                'verbose_name_plural': 'تنبيهات المخزون',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('part',), name='one_active_alert_per_part')],
            },
        ),
        migrations.CreateModel(
            name='PartUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية المصروفة')),
                ('unit_purchase_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر الشراء وقت الصرف')),
                ('unit_sale_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر البيع وقت الصرف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_usages_added', to=settings.AUTH_USER_MODEL)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_usages', to='workshop.jobcard')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='inventory.part')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='accounts.workshop')),
            ],
            options={
                'verbose_name': 'صرف قطعة',
                'verbose_name_plural': 'حركات صرف القطع',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['workshop', 'job_card'], name='inventory_p_worksho_acd907_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('workshop', 'name'), name='unique_supplier_per_workshop'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['workshop', 'quantity', 'reorder_level'], name='inventory_p_worksho_384684_idx'),
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.UniqueConstraint(fields=('workshop', 'sku'), name='unique_sku_per_workshop'),
        ),
    ]
