import { useEffect, useState } from 'react'
import { emptyExpense, emptyVoucher } from './AccountingDefaults.js'
import Pagination from './Pagination.jsx'
import { usePagination } from './usePagination.js'

function PaginatedSection({ title, countLabel, items, pagination, itemLabel, emptyMessage, renderItem, listClassName = 'record-list', description }) {
  return <section className="recent-jobs">
    <div className="section-heading"><div><h2>{title}</h2>{description && <p>{description}</p>}</div><span>{countLabel}</span></div>
    {items.length ? <>
      <div className={listClassName}>{pagination.pageItems.map(renderItem)}</div>
      <Pagination {...pagination} onPageChange={pagination.setPage} itemLabel={itemLabel} />
    </> : <p className="empty-state">{emptyMessage}</p>}
  </section>
}

export default function AccountingPage({ jobs, invoices, expenses, vouchers, profitLoss, expense, setExpense, voucher, setVoucher, submit, update, onCreateInvoice, onGeneratePdf, onRecordPayment, remove, pageSize }) {
  const [jobCard, setJobCard] = useState('')
  const [payments, setPayments] = useState({})
  const billableJobs = jobs.filter((item) => ['ready', 'delivered'].includes(item.status) && !invoices.some((invoice) => invoice.job_card === item.id))
  const invoicePagination = usePagination(invoices, pageSize)
  const editorPagination = usePagination(invoices, pageSize)
  const voucherPagination = usePagination(vouchers, pageSize)
  const expensePagination = usePagination(expenses, pageSize)

  return <>
    <section className="dashboard-intro"><div><h2>المحاسبة والتقارير</h2><p>أنشئ الفاتورة من بطاقة العمل الجاهزة، ثم سجّل المصروفات والمدفوعات.</p></div></section>
    <section className="financial-grid"><article><span>الإيرادات قبل الضريبة</span><strong>{Number(profitLoss?.revenue || 0).toFixed(2)} ر.س</strong></article><article><span>تكلفة قطع الغيار</span><strong>{Number(profitLoss?.parts_cost || 0).toFixed(2)} ر.س</strong></article><article><span>المصروفات</span><strong>{Number(profitLoss?.expenses || 0).toFixed(2)} ر.س</strong></article><article className="positive"><span>صافي الربح</span><strong>{Number(profitLoss?.net_profit || 0).toFixed(2)} ر.س</strong></article></section>
    <section className="form-card"><h3>إنشاء فاتورة من بطاقة عمل</h3><form className="entry-form" onSubmit={(event) => { event.preventDefault(); if (jobCard) { onCreateInvoice(jobCard); setJobCard('') } }}><label>بطاقة جاهزة أو مسلّمة<select required value={jobCard} onChange={(event) => setJobCard(event.target.value)}><option value="">اختر البطاقة</option>{billableJobs.map((item) => <option key={item.id} value={item.id}>{item.job_number} — {item.vehicle_label}</option>)}</select></label><button className="primary">إنشاء الفاتورة</button></form></section>
    <PaginatedSection title="الفواتير" countLabel={`${invoices.length} فاتورة`} items={invoices} pagination={invoicePagination} itemLabel="فاتورة" emptyMessage="لا توجد فواتير بعد." renderItem={(item) => <div className="invoice-row" key={item.id}><div><strong>{item.invoice_number}</strong><small>{item.customer_name} · {item.vehicle_label}</small></div><span className="job-status">{item.status_label}</span><strong>{item.total} ر.س</strong><div className="invoice-actions">{item.status !== 'paid' && item.status !== 'void' && <><input aria-label={`مبلغ دفعة ${item.invoice_number}`} type="number" min="0.01" max={Math.max(0, Number(item.total) - Number(item.amount_paid))} step="0.01" placeholder="دفعة" value={payments[item.id] || ''} onChange={(event) => setPayments({ ...payments, [item.id]: event.target.value })} /><button className="text-action" type="button" onClick={() => { if (payments[item.id]) onRecordPayment(item.id, payments[item.id]) }}>تحصيل</button></>}<button className="text-action" type="button" onClick={() => onGeneratePdf(item.id)}>PDF</button></div></div>} />
    <InvoiceManagement invoices={invoices} pagination={editorPagination} submit={submit} update={update} remove={remove} />
    <Vouchers vouchers={vouchers} invoices={invoices} voucher={voucher} setVoucher={setVoucher} submit={submit} pagination={voucherPagination} />
    <section className="form-card"><h3>تسجيل مصروف</h3><form className="entry-form" onSubmit={(event) => submit(event, '/accounting/expenses/', expense, () => setExpense(emptyExpense), 'تم تسجيل المصروف.')}><label>الفئة<select value={expense.category} onChange={(event) => setExpense({ ...expense, category: event.target.value })}><option value="rent">إيجار</option><option value="salary">رواتب</option><option value="utilities">خدمات ومرافق</option><option value="supplies">مستلزمات</option><option value="other">أخرى</option></select></label><label>الوصف<input required value={expense.description} onChange={(event) => setExpense({ ...expense, description: event.target.value })} /></label><label>المبلغ<input required type="number" min="0.01" step="0.01" value={expense.amount} onChange={(event) => setExpense({ ...expense, amount: event.target.value })} /></label><label>التاريخ<input required type="date" value={expense.occurred_at} onChange={(event) => setExpense({ ...expense, occurred_at: event.target.value })} /></label><label>المرجع<input value={expense.reference} onChange={(event) => setExpense({ ...expense, reference: event.target.value })} /></label><button className="primary">تسجيل المصروف</button></form></section>
    <PaginatedSection title="آخر المصروفات" countLabel={`${expenses.length} سجل`} items={expenses} pagination={expensePagination} itemLabel="مصروف" emptyMessage="لا توجد مصروفات مسجلة." renderItem={(item) => <div className="record-row" key={item.id}><strong>{item.description}</strong><span>{item.category}</span><span>{item.occurred_at}</span><strong>{item.amount} ر.س</strong><button className="delete-action" type="button" onClick={() => remove('/accounting/expenses/', item.id)}>حذف</button></div>} />
  </>
}

function InvoiceManagement({ invoices, pagination, submit, update, remove }) {
  return <PaginatedSection title="تعديل بنود الفاتورة" countLabel={`${invoices.length} فاتورة`} description="يمكن تصحيح الفاتورة ما دامت مسودة وقبل إصدارها أو تسجيل أي دفعة." items={invoices} pagination={pagination} itemLabel="محرر فاتورة" emptyMessage="لا توجد فواتير بعد." listClassName="invoice-editor-list" renderItem={(invoice) => invoice.status === 'draft' ? <InvoiceDraftEditor key={invoice.id} invoice={invoice} submit={submit} update={update} remove={remove} /> : <div className="invoice-editor locked" key={invoice.id}><div><strong>{invoice.invoice_number}</strong><small>الفاتورة {invoice.status_label} ومحفوظة للقراءة فقط.</small></div>{invoice.lines.map((line) => <div className="invoice-line-summary" key={line.id}><span>{line.description}</span><span>{line.quantity} × {line.unit_price} ر.س</span><strong>{line.line_total} ر.س</strong></div>)}</div>} />
}

function InvoiceDraftEditor({ invoice, submit, update, remove }) {
  const [metadata, setMetadata] = useState({ vat_rate: invoice.vat_rate, due_at: invoice.due_at || '', notes: invoice.notes || '' })
  const [lineDrafts, setLineDrafts] = useState(() => Object.fromEntries(invoice.lines.map((line) => [line.id, { description: line.description, quantity: line.quantity, unit_price: line.unit_price, line_type: line.line_type }])))
  const [newLine, setNewLine] = useState({ line_type: 'adjustment', description: '', quantity: '1.00', unit_price: '' })

  useEffect(() => {
    setMetadata({ vat_rate: invoice.vat_rate, due_at: invoice.due_at || '', notes: invoice.notes || '' })
    setLineDrafts(Object.fromEntries(invoice.lines.map((line) => [line.id, { description: line.description, quantity: line.quantity, unit_price: line.unit_price, line_type: line.line_type }])))
  }, [invoice])

  const changeLine = (lineId, field, value) => setLineDrafts({ ...lineDrafts, [lineId]: { ...lineDrafts[lineId], [field]: value } })
  return <div className="invoice-editor"><div className="section-heading"><div><strong>{invoice.invoice_number}</strong><small>{invoice.customer_name} · الإجمالي الحالي {invoice.total} ر.س</small></div><span className="job-status draft">مسودة قابلة للتعديل</span></div>
    <form className="entry-form invoice-metadata" onSubmit={async (event) => { event.preventDefault(); await update(`/accounting/invoices/${invoice.id}/`, { ...metadata, due_at: metadata.due_at || null }, 'تم تحديث بيانات الفاتورة وإعادة احتسابها.') }}><label>نسبة الضريبة %<input required type="number" min="0" step="0.01" value={metadata.vat_rate} onChange={(event) => setMetadata({ ...metadata, vat_rate: event.target.value })} /></label><label>تاريخ الاستحقاق<input type="date" value={metadata.due_at} onChange={(event) => setMetadata({ ...metadata, due_at: event.target.value })} /></label><label>ملاحظات<input value={metadata.notes} onChange={(event) => setMetadata({ ...metadata, notes: event.target.value })} /></label><button className="primary">حفظ بيانات الفاتورة</button></form>
    <div className="invoice-lines-edit">{invoice.lines.map((line) => { const draft = lineDrafts[line.id] || line; return <form className="invoice-line-edit" key={line.id} onSubmit={async (event) => { event.preventDefault(); await update(`/accounting/invoice-lines/${line.id}/`, draft, 'تم تصحيح بند الفاتورة وإعادة احتساب الإجمالي.') }}><label>نوع البند<select value={draft.line_type} onChange={(event) => changeLine(line.id, 'line_type', event.target.value)}><option value="service">خدمة</option><option value="part">قطعة غيار</option><option value="adjustment">تعديل</option></select></label><label>الوصف<input required value={draft.description} onChange={(event) => changeLine(line.id, 'description', event.target.value)} /></label><label>الكمية<input required type="number" min="0.01" step="0.01" value={draft.quantity} onChange={(event) => changeLine(line.id, 'quantity', event.target.value)} /></label><label>سعر الوحدة<input required type="number" min="0" step="0.01" value={draft.unit_price} onChange={(event) => changeLine(line.id, 'unit_price', event.target.value)} /></label><strong>{line.line_total} ر.س</strong><button className="text-action" type="submit">حفظ</button><button className="delete-action" type="button" onClick={() => remove('/accounting/invoice-lines/', line.id)}>حذف</button></form> })}</div>
    <form className="entry-form add-invoice-line" onSubmit={(event) => submit(event, '/accounting/invoice-lines/', { ...newLine, invoice: invoice.id }, () => setNewLine({ line_type: 'adjustment', description: '', quantity: '1.00', unit_price: '' }), 'تمت إضافة بند وإعادة احتساب الفاتورة.')}><label>نوع البند<select value={newLine.line_type} onChange={(event) => setNewLine({ ...newLine, line_type: event.target.value })}><option value="service">خدمة</option><option value="part">قطعة غيار</option><option value="adjustment">تعديل</option></select></label><label>وصف البند<input required value={newLine.description} onChange={(event) => setNewLine({ ...newLine, description: event.target.value })} /></label><label>الكمية<input required type="number" min="0.01" step="0.01" value={newLine.quantity} onChange={(event) => setNewLine({ ...newLine, quantity: event.target.value })} /></label><label>سعر الوحدة<input required type="number" min="0" step="0.01" value={newLine.unit_price} onChange={(event) => setNewLine({ ...newLine, unit_price: event.target.value })} /></label><button className="primary">إضافة بند</button></form>
  </div>
}

function Vouchers({ vouchers, invoices, voucher, setVoucher, submit, pagination }) {
  const isReceipt = voucher.voucher_type === 'receipt'
  const payableInvoices = invoices.filter((item) => !['draft', 'void', 'paid'].includes(item.status))
  const chooseInvoice = (invoiceId) => {
    const invoice = payableInvoices.find((item) => item.id === Number(invoiceId))
    setVoucher({ ...voucher, invoice: invoiceId, party_name: invoice?.customer_name || voucher.party_name, amount: invoice ? Math.max(0, Number(invoice.total) - Number(invoice.amount_paid)).toFixed(2) : voucher.amount })
  }
  const switchType = (voucherType) => setVoucher({ ...emptyVoucher, voucher_type: voucherType })
  return <>
    <section className="form-card"><h3>سند قبض أو صرف</h3><form className="entry-form" onSubmit={(event) => submit(event, '/accounting/vouchers/', { ...voucher, invoice: isReceipt ? voucher.invoice || null : null }, () => setVoucher(emptyVoucher), 'تم إنشاء السند المحاسبي.')}><label>نوع السند<select value={voucher.voucher_type} onChange={(event) => switchType(event.target.value)}><option value="receipt">سند قبض</option><option value="disbursement">سند صرف</option></select></label>{isReceipt && <label>الفاتورة<select required value={voucher.invoice} onChange={(event) => chooseInvoice(event.target.value)}><option value="">اختر الفاتورة</option>{payableInvoices.map((item) => <option key={item.id} value={item.id}>{item.invoice_number} — {item.customer_name}</option>)}</select></label>}<label>الجهة<input required value={voucher.party_name} onChange={(event) => setVoucher({ ...voucher, party_name: event.target.value })} /></label><label>المبلغ<input required type="number" min="0.01" step="0.01" value={voucher.amount} onChange={(event) => setVoucher({ ...voucher, amount: event.target.value })} /></label><label>التاريخ<input required type="date" value={voucher.occurred_at} onChange={(event) => setVoucher({ ...voucher, occurred_at: event.target.value })} /></label>{isReceipt ? <label>وسيلة القبض<select value={voucher.payment_method} onChange={(event) => setVoucher({ ...voucher, payment_method: event.target.value })}><option value="cash">نقدي</option><option value="card">بطاقة</option><option value="transfer">تحويل</option><option value="other">أخرى</option></select></label> : <label>فئة المصروف<select value={voucher.category} onChange={(event) => setVoucher({ ...voucher, category: event.target.value })}><option value="rent">إيجار</option><option value="salary">رواتب</option><option value="utilities">خدمات ومرافق</option><option value="supplies">مستلزمات</option><option value="other">أخرى</option></select></label>}<label>المرجع<input value={voucher.reference} onChange={(event) => setVoucher({ ...voucher, reference: event.target.value })} /></label><label className="wide">البيان<input required value={voucher.description} onChange={(event) => setVoucher({ ...voucher, description: event.target.value })} /></label><button className="primary">إنشاء السند</button></form></section>
    <PaginatedSection title="سندات القبض والصرف" countLabel={`${vouchers.length} سند`} items={vouchers} pagination={pagination} itemLabel="سند" emptyMessage="لا توجد سندات محاسبية بعد." renderItem={(item) => <div className="record-row" key={item.id}><strong>{item.voucher_number}</strong><span>{item.voucher_type_label} · {item.party_name}</span><span>{item.description}</span><strong>{item.amount} ر.س</strong></div>} />
  </>
}
