import Pagination from './Pagination.jsx'
import { usePagination } from './usePagination.js'

function PaginatedSection({ title, countLabel, items, renderItem, emptyMessage, pagination, itemLabel, listClassName = 'record-list' }) {
  return <section className="recent-jobs">
    <div className="section-heading"><h2>{title}</h2><span>{countLabel}</span></div>
    {items.length ? <>
      <div className={listClassName}>{pagination.pageItems.map(renderItem)}</div>
      <Pagination {...pagination} onPageChange={pagination.setPage} itemLabel={itemLabel} />
    </> : <p className="empty-state">{emptyMessage}</p>}
  </section>
}

export default function InventoryPage({ suppliers, parts, lowStock, alerts, partUsages, partRequests, jobs, supplier, setSupplier, part, setPart, partUsage, setPartUsage, partRequest, setPartRequest, onSaveSupplier, onCancelSupplier, onSubmitPart, onSubmitUsage, onSubmitRequest, onDeleteSupplier, onDeletePart, onAcknowledge, onReviewRequest, canManage, canIssue, isTechnician, pageSize }) {
  const activeJobs = jobs.filter((item) => ['pending', 'in_progress'].includes(item.status))
  const activeAlerts = alerts.filter((item) => item.is_active)
  const supplierPagination = usePagination(suppliers, pageSize)
  const requestPagination = usePagination(partRequests, pageSize)
  const partPagination = usePagination(parts, pageSize)
  const alertPagination = usePagination(activeAlerts, pageSize)
  const usagePagination = usePagination(partUsages, pageSize)

  return <>
    <section className="dashboard-intro"><div><h2>{isTechnician ? 'طلبات قطع الغيار' : 'المخزون وقطع الغيار'}</h2><p>{isTechnician ? 'اطلب القطعة مباشرة للبطاقة المسندة إليك وتابع حالة الصرف.' : 'تُراجع الطلبات ثم تخصم الكمية تلقائياً عند الصرف.'}</p></div></section>
    <section className="inventory-summary"><article><span>قطع نشطة</span><strong>{parts.filter((item) => item.is_active).length}</strong></article><article className="warning"><span>تحت حد الطلب</span><strong>{lowStock.length}</strong></article><article><span>طلبات معلقة</span><strong>{partRequests.filter((item) => ['requested', 'approved'].includes(item.status)).length}</strong></article></section>
    {isTechnician && <section className="form-card"><h3>طلب قطعة غيار</h3><form className="entry-form" onSubmit={onSubmitRequest}><label>بطاقة العمل<select required value={partRequest.job_card} onChange={(e) => setPartRequest({ ...partRequest, job_card: e.target.value })}><option value="">اختر البطاقة</option>{activeJobs.map((item) => <option key={item.id} value={item.id}>{item.job_number} — {item.vehicle_label}</option>)}</select></label><label>قطعة الغيار<select required value={partRequest.part} onChange={(e) => setPartRequest({ ...partRequest, part: e.target.value })}><option value="">اختر القطعة</option>{parts.filter((item) => item.is_active).map((item) => <option key={item.id} value={item.id}>{item.sku} — {item.name} ({item.quantity} متاح)</option>)}</select></label><label>الكمية<input required type="number" min="1" value={partRequest.quantity} onChange={(e) => setPartRequest({ ...partRequest, quantity: e.target.value })} /></label><label className="wide">ملاحظات<textarea value={partRequest.notes} onChange={(e) => setPartRequest({ ...partRequest, notes: e.target.value })} /></label><button className="primary">إرسال الطلب</button></form></section>}
    {canManage && <>
      <section className="form-card"><h3>{supplier.id ? 'تحديث المورد' : 'إضافة مورد'}</h3><form className="entry-form" onSubmit={onSaveSupplier}><label>اسم المورد<input required value={supplier.name} onChange={(e) => setSupplier({ ...supplier, name: e.target.value })} /></label><label>جهة الاتصال<input value={supplier.contact_name} onChange={(e) => setSupplier({ ...supplier, contact_name: e.target.value })} /></label><label>الهاتف<input value={supplier.phone} onChange={(e) => setSupplier({ ...supplier, phone: e.target.value })} /></label><label>البريد<input type="email" value={supplier.email} onChange={(e) => setSupplier({ ...supplier, email: e.target.value })} /></label><label className="wide">ملاحظات<textarea value={supplier.notes} onChange={(e) => setSupplier({ ...supplier, notes: e.target.value })} /></label><button className="primary">{supplier.id ? 'حفظ التحديث' : 'إضافة المورد'}</button>{supplier.id && <button type="button" className="subtle" onClick={onCancelSupplier}>إلغاء</button>}</form></section>
      <PaginatedSection title="الموردون" countLabel={`${suppliers.length} مورد`} items={suppliers} pagination={supplierPagination} itemLabel="مورد" emptyMessage="لا يوجد موردون بعد." renderItem={(item) => <div className="record-row" key={item.id}><strong>{item.name}</strong><span>{item.contact_name || '—'} · {item.phone || '—'}</span><span>{item.email || '—'}</span><button className="text-action" type="button" onClick={() => setSupplier(item)}>تعديل</button><button className="delete-action" type="button" onClick={() => onDeleteSupplier(item.id)}>حذف</button></div>} />
      <section className="form-card"><h3>إضافة قطعة غيار</h3><form className="entry-form" onSubmit={onSubmitPart}><label>اسم القطعة<input required value={part.name} onChange={(e) => setPart({ ...part, name: e.target.value })} /></label><label>رمز القطعة<input required value={part.sku} onChange={(e) => setPart({ ...part, sku: e.target.value })} /></label><label>المورد<select value={part.supplier} onChange={(e) => setPart({ ...part, supplier: e.target.value })}><option value="">بدون مورد</option>{suppliers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>الكمية الحالية<input required type="number" min="0" value={part.quantity} onChange={(e) => setPart({ ...part, quantity: e.target.value })} /></label><label>حد إعادة الطلب<input required type="number" min="0" value={part.reorder_level} onChange={(e) => setPart({ ...part, reorder_level: e.target.value })} /></label><label>سعر الشراء<input required type="number" min="0" step="0.01" value={part.purchase_price} onChange={(e) => setPart({ ...part, purchase_price: e.target.value })} /></label><label>سعر البيع<input required type="number" min="0" step="0.01" value={part.sale_price} onChange={(e) => setPart({ ...part, sale_price: e.target.value })} /></label><button className="primary">إضافة القطعة</button></form></section>
    </>}
    {canIssue && <section className="form-card"><h3>صرف مباشر</h3><form className="entry-form" onSubmit={onSubmitUsage}><label>بطاقة العمل<select required value={partUsage.job_card} onChange={(e) => setPartUsage({ ...partUsage, job_card: e.target.value })}><option value="">اختر البطاقة</option>{activeJobs.map((item) => <option key={item.id} value={item.id}>{item.job_number} — {item.vehicle_label}</option>)}</select></label><label>قطعة الغيار<select required value={partUsage.part} onChange={(e) => setPartUsage({ ...partUsage, part: e.target.value })}><option value="">اختر القطعة</option>{parts.filter((item) => item.is_active).map((item) => <option key={item.id} value={item.id}>{item.sku} — {item.name} ({item.quantity})</option>)}</select></label><label>الكمية<input required type="number" min="1" value={partUsage.quantity} onChange={(e) => setPartUsage({ ...partUsage, quantity: e.target.value })} /></label><button className="primary">صرف القطعة</button></form></section>}
    <PaginatedSection title="طلبات القطع" countLabel={`${partRequests.length} طلب`} items={partRequests} pagination={requestPagination} itemLabel="طلب" emptyMessage="لا توجد طلبات قطع." renderItem={(item) => <div className="record-row" key={item.id}><strong>{item.job_number} — {item.part_name}</strong><span>{item.requested_by_name} · {item.quantity} قطعة</span><span className="job-status">{item.status_label}</span>{canIssue && ['requested', 'approved'].includes(item.status) && <><button className="text-action" type="button" onClick={() => onReviewRequest(item.id, 'fulfill')}>صرف</button><button className="delete-action" type="button" onClick={() => onReviewRequest(item.id, 'reject')}>رفض</button></>}</div>} />
    <PaginatedSection title="قطع الغيار" countLabel={`${parts.length} قطعة`} items={parts} pagination={partPagination} itemLabel="قطعة" emptyMessage="لا توجد قطع غيار." renderItem={(item) => <div className={`record-row ${item.is_low_stock ? 'low-stock-row' : ''}`} key={item.id}><strong>{item.sku} — {item.name}</strong><span>{item.quantity} متاح / حد الطلب {item.reorder_level}</span><span>{item.supplier_name || 'بدون مورد'} · {item.sale_price} ر.س</span>{canManage && <button className="delete-action" type="button" onClick={() => onDeletePart(item.id)}>حذف</button>}</div>} />
    {canManage && <PaginatedSection title="تنبيهات الحد الأدنى" countLabel={`${activeAlerts.length} فعّال`} items={activeAlerts} pagination={alertPagination} itemLabel="تنبيه" emptyMessage="لا توجد تنبيهات حد أدنى فعّالة." renderItem={(item) => <div className="record-row low-stock-row" key={item.id}><strong>{item.part_sku} — {item.part_name}</strong><span>المتاح: {item.quantity_at_alert}</span><button className="text-action" type="button" onClick={() => onAcknowledge(item.id)}>تأكيد الاطلاع</button></div>} />}
    {!isTechnician && <PaginatedSection title="آخر حركات الصرف" countLabel={`${partUsages.length} حركة`} items={partUsages} pagination={usagePagination} itemLabel="حركة" emptyMessage="لا توجد حركات صرف بعد." renderItem={(item) => <div className="record-row" key={item.id}><strong>{item.job_number} — {item.part_sku}</strong><span>{item.part_name}</span><span>{item.quantity} × {item.unit_sale_price} ر.س</span></div>} />}
  </>
}
