# Generated by Django 5.2.17 on 2026-08-08 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('workforce', '0001_initial'),
        ('workshop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='اسم الوثيقة')),
                ('document_type', models.CharField(max_length=100, verbose_name='نوع الوثيقة')),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('encrypted_file', models.FileField(upload_to='documents/%Y/%m/')),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='workshop.customer')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='workforce.employee')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='workshop.vehicle')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='accounts.workshop')),
            ],
            options={
                'verbose_name': 'وثيقة',
                'verbose_name_plural': 'الوثائق',
                'ordering': ('expires_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='DocumentExpiryAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before', models.PositiveSmallIntegerField()),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiry_alerts', to='documents.document')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='accounts.workshop')),
            ],
            options={
                'verbose_name': 'تنبيه انتهاء وثيقة',
                'verbose_name_plural': 'تنبيهات انتهاء الوثائق',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['workshop', 'expires_at'], name='documents_d_worksho_ff88f1_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['workshop', 'document_type'], name='documents_d_worksho_e9bdb3_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentexpiryalert',
            constraint=models.UniqueConstraint(fields=('document', 'days_before'), name='one_expiry_alert_per_threshold'),
        ),
    ]
