# Generated by Django 5.2.17 on 2026-08-08 19:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('workshop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(default='فني', max_length=100, verbose_name='المسمى الوظيفي')),
                ('hired_at', models.DateField(verbose_name='تاريخ التوظيف')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='نسبة العمولة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='accounts.workshop')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفون',
                'ordering': ('user__first_name', 'user__username'),
            },
        ),
        migrations.CreateModel(
            name='EmployeeCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='فترة الاستحقاق')),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('basis_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قيمة العمل بعد التوزيع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قيمة العمولة')),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='workforce.employee')),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='workshop.jobcard')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='accounts.workshop')),
            ],
            options={
                'verbose_name': 'عمولة موظف',
                'verbose_name_plural': 'عمولات الموظفين',
                'ordering': ('-period', 'employee__user__first_name'),
                'indexes': [models.Index(fields=['workshop', 'period'], name='workforce_e_worksho_3db1fb_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'job_card'), name='one_commission_per_employee_job')],
            },
        ),
        migrations.CreateModel(
            name='JobTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='اسم المهمة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('status', models.CharField(choices=[('not_started', 'لم تبدأ'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة')], default='not_started', max_length=20)),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='الساعات التقديرية')),
                ('actual_minutes', models.PositiveIntegerField(default=0, verbose_name='الدقائق الفعلية')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='workforce.employee')),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='workshop.jobcard')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='accounts.workshop')),
            ],
            options={
                'verbose_name': 'مهمة',
                'verbose_name_plural': 'المهام',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['workshop', 'employee', 'status'], name='workforce_j_worksho_776249_idx'), models.Index(fields=['workshop', 'job_card'], name='workforce_j_worksho_ab2970_idx')],
            },
        ),
    ]
